### ISSUE TITLE
README is misleading

### ISSUE THREAD

**Issue by EvelynTSMG** [SSXModding/SSX-ElfLdr#12]
"Quasi-bigless" is required for Tricky, similarly to OG, as per https://discord.com/channels/864206854745358386/864206854745358389/965716268495806484

Sorry for the semi-pointless issue btw

**Comment by modeco80** [comment]
I know, documentation is kinda in flux because i havent produced a real "1.0" version and ideally i would like to have an automatic setup tool do the work
